name: Manual Build VW

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run build script
        id: bugtool
        run: |
          python build/py/bugtool.py publish --github vw

      - name: Show outputs
        run: |
          echo "Commit:      ${{ steps.bugtool.outputs.commit }}"
          echo "Branch:      ${{ steps.bugtool.outputs.branch }}"
          echo "Variant ID:  ${{ steps.bugtool.outputs.variantid }}"
          echo "Version:     ${{ steps.bugtool.outputs.version }}"
          echo "Result File: ${{ steps.bugtool.outputs.resultfile }}"
